spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 176293245373-3onel5si4cldsjqcbbciv1o0fkik1cdi.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: QrN_WicURPUtqt6iauuU
            client-secret: ZNLB_aNIOo
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 751e577353db975895189937a70c2f88
            client-secret: xUqEk54Zj5gHVZFANc2DX4HfoeFLynF2
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id