= REST Docs 문서 만들기 (글의 제목)
SsangJoon (GTD)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:
:docinfo: shared-head

[[Member-API]]
== Member API

[[Member-생성]]
=== Member 생성
operation::member-controller-test/member_create[snippets='http-request,request-fields,http-response']

[[Member-리스트-조회]]
=== Member 리스트 조회
operation::member-controller-test/member_list[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-단일-조회]]
=== Member 단일 조회
operation::member-controller-test/member_get[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-수정]]
=== Member 수정
operation::member-controller-test/member_modify[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-삭제]]
=== Member 삭제
operation::member-controller-test/member_delete[snippets='http-request,path-parameters,http-response,response-fields']

[[Login-API]]
== Login API

[[Login]]
=== Login
operation::login-controller-test/login[snippets='http-request,request-fields,http-response']