= Getting Things Done
SsangJoon (GTD)
:sectnums:
:doctype: book
:toc: left
//:icons: font
:source-highlighter: prettify
:toclevels: 2
:toc-title: Table of Contents
:sectlinks:
:docinfo: shared-head

GettingThingsDone 프로세스를 구현하는 개인 프로젝트 입니다.


1. 로그인(Login), 회원가입(JoinUp)을 제외한 모든 요청에는 AccessToken이 필요 합니다. +
2. 지정된 TOKEN_HEADER_PREFIX을 토큰과 함께 헤더에 기재하여 요청하여야 인증이 가능합니다.

[[Member-API]]
== Member API

[[Member-생성]]
=== Member joinUp +
Password는 차후 정규식으로 검증할 예정

operation::member-controller-test/member_create[snippets='http-request,request-fields,http-response']

[[Member-단일-조회]]
=== Member get
operation::member-controller-test/member_get[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-리스트-조회]]
=== Member list
operation::member-controller-test/member_list[snippets='http-request,http-response,response-fields']

[[Member-수정]]
=== Member update
operation::member-controller-test/member_modify[snippets='http-request,http-response,response-fields']

[[Member-삭제]]
=== Member delete
operation::member-controller-test/member_delete[snippets='http-request,path-parameters,http-response']



[[Login-API]]
== Login API

[[Login]]
=== Login +
Access Token과 Refresh Token을 발행합니다.

operation::login-controller-test/login[snippets='http-request,request-fields,http-response']

[[Logout]]
=== Logout
operation::login-controller-test/logout[snippets='http-request,request-fields,http-response']

[[Refresh]]
=== Refresh
Access Token 만료 시 Refresh Token과 함께 request header에 담아 재요청합니다.

operation::login-controller-test/refresh[snippets='http-request,http-response,response-fields']





[[Things-API]]
== Things API

[[Collect-등록]]
=== Collect create
operation::things-controller-test/collect_post[snippets='http-request,http-response,response-fields']

[[Collect-단일-조회]]
=== Collect get
operation::things-controller-test/collect_get[snippets='http-request,path-parameters,http-response,response-fields']

[[Collect-조회]]
=== Collect list
operation::things-controller-test/collect_list[snippets='http-request,http-response,response-fields']

[[Collect-수정]]
=== Collect update
operation::things-controller-test/collect_put[snippets='http-request,http-response,response-fields']

[[Collect-삭제]]
=== Collect delete
operation::things-controller-test/collect_delete[snippets='http-request,path-parameters,http-response']


[[MatCol-create]]
=== MatCol create
operation::things-controller-test/material[snippets='http-request,request-parts,path-parameters,http-response']

[[MatCol-fileUpload-create]]
=== MatCol create & fileUpload
operation::things-controller-test/material_file[snippets='http-request,request-parts,http-response']


//[snippets='http-request,path-parameters,http-response,response-fields']