= Getting Things Done
SsangJoon (GTD)
:sectnums:
:doctype: book
:toc: left
:icons: font
:source-highlighter: highlightjs
:toclevels: 2
:toc-title: Table of Contents
:sectlinks:
:docinfo: shared-head

GettingThingsDone 프로세스를 구현하는 개인 프로젝트 입니다.

[[Login-API]]
== Login API

[[Login]]
=== Login +
Access Token과 Refresh Token을 발행합니다. +
(Access Token : 10분, Refresh Token : 14일 (2주))

operation::login-controller-test/login[snippets='http-request,request-fields,http-response']

[[Logout]]
=== Logout +
Redis를 통해 토큰을 블랙리스트로 등록합니다.

operation::login-controller-test/logout[snippets='http-request,http-response']

[[Refresh]]
=== Refresh
Access Token 만료 시 Refresh Token과 함께 request header에 담아 재요청합니다. +
리프레시 토큰은 남은 만료 기간을 계산하고 5초 미만이라면 재발급합니다.

operation::login-controller-test/refresh[snippets='http-request,http-response,response-fields']




[[Member-API]]
== Member API

[[Member-생성]]
=== Member create +
operation::member-controller-test/member_create[snippets='http-request,request-fields,http-response']

[[Member-리스트-조회]]
=== Member list
operation::member-controller-test/member_list[snippets='http-request,http-response,response-fields']

[[Member-단일-조회]]
=== Member get
operation::member-controller-test/member_get[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-수정]]
=== Member update
operation::member-controller-test/member_modify[snippets='http-request,request-fields,http-response,response-fields']

[[Member-삭제]]
=== Member delete
operation::member-controller-test/member_delete[snippets='http-request,path-parameters,http-response']



[[Things-API]]
== Things API

[[Collect-등록]]
=== Collect create
operation::things-controller-test/collect_post[snippets='http-request,request-fields,http-response,response-fields']

[[Collect-단일-조회]]
=== Collect get
operation::things-controller-test/collect_get[snippets='http-request,path-parameters,http-response,response-fields']

[[Collect-조회]]
=== Collect list
operation::things-controller-test/collect_list[snippets='http-request,http-response,response-fields']

[[Collect-수정]]
=== Collect update
operation::things-controller-test/collect_put[snippets='http-request,request-fields,http-response,response-fields']

[[Collect-삭제]]
=== Collect delete
operation::things-controller-test/collect_delete[snippets='http-request,path-parameters,http-response']


[[MatCol-create]]
=== MatCol create +

operation::things-controller-test/material[snippets='http-request,request-parts,http-response']

[[MatCol-fileUpload-create]]
=== MatCol create & fileUpload
operation::things-controller-test/material_file[snippets='http-request,request-parts,http-response']


